### ISSUE TITLE
Infografia RA-Christopher Garcia

### ISSUE THREAD

**Issue by Christopherg2** [SistemasTecTlaxiaco/infografia-Christopherg2#1]
[Infografia RA- Christopher Garcia Garcia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Christopherg2/files/8055026/Infografia.RA-.Christopher.Garcia.Garcia.pdf)

**Comment by Jaimer117** [comment]
calificación 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
